pages/urls.py
from django.urls import path
from . import views

urlpatterns = []

for view_class in views.pages:
    urlpatterns.append(path(view_class.Meta.path, view_class.as_view(), name=view_class.Meta.page_name))

threecross_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from surveys import views as survey_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('apply', user_views.apply_view, name='apply'),
    path('members/password/change/', user_views.login_after_password_change, name='account_change_password'),
    path('members/', user_views.profile_view, name='profile'),
    path('members/', include('allauth.urls')),
    path('members/surveys/<slug:slug>,<int:id>', survey_views.survey_view, name="survey"),
    path('ajax/survey_vote', survey_views.ajax_vote_view, name="survey_vote"),
    path('members/nominate_charity', survey_views.nominate_charity_view, name="nominate_charity")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

addresses/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField


class Address(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street = models.CharField('Street Address', max_length=256, blank=False)
    unit = models.CharField('Unit #', max_length=256, blank=True)
    city = models.CharField(max_length=256, blank=False)
    state = models.CharField(max_length=2, blank=False)
    postal_code = models.CharField('Postal Code', max_length=10, blank=False)
    phone_number = PhoneNumberField('Phone Number')

businesses/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from addresses.models import Address


class Business(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=256)
    website = models.URLField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.user_id is None:
            u = get_user_model()()
            u.save()
            self.user_id = u.id
        super(Business, self).save(*args, **kwargs)

    def is_active(instance):
        try:
            return instance.user.is_active
        except:
            return True

    @property
    def full_name(instance):
        return instance.name

    @property
    def sort_name(instance):
        starts_with_flags = [
            'the ',
            'an ',
            'a '
        ]

        for flag in starts_with_flags:
            if instance.name.lower().startswith(flag):
                return "%s, %s" % (instance.name[len(flag):], instance.name[:len(flag)-1])
            else:
                pass
        return instance.name

surveys/models.py
from django.db import models
from django.urls import reverse

from threecross_site import settings
from autoslug import AutoSlugField


class Survey(models.Model):
    title = models.CharField(max_length=256, blank=False, null=False)
    slug = AutoSlugField(populate_from='title')
    real_time_results = models.BooleanField(blank=False, null=False, default=False)
    max_responses = models.IntegerField(blank=False, null=False, default=0)
    template = models.CharField(max_length=128, blank=True, null=True)
    ajax_template = models.CharField(max_length=128, blank=True, null=True)
    sort_questions = models.BooleanField(blank=False, null=False, default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('survey', kwargs={'slug': self.slug, 'id': self.id})

    @property
    def question_dict(self):
        qd = {}
        for q in self.surveyquestion_set.all():
            qd[q.id] = q
        return qd

    def get_response_for(self, user):
        sr = None
        if user.is_authenticated:
            try:
                sr = SurveyResponse.objects.get(survey=self, user=user)
            except SurveyResponse.DoesNotExist:
                sr = SurveyResponse()
                sr.user = user
                sr.survey = self
                sr.save()

        return sr


class SurveyQuestion(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, blank=False, null=False)
    short_name = models.CharField(max_length=256, blank=False, null=False)
    prompt = models.TextField(blank=False, null=False)
    required = models.BooleanField(blank=False, null=False, default=False)
    order = models.IntegerField(blank=False, null=False, default=0)

    YES_NO = "YN"
    FREEFORM = "FF"

    type = models.CharField(
        max_length=3,
        choices=[(YES_NO, 'Yes/No'), (FREEFORM, 'Freeform')],
        default=FREEFORM
    )

    def __str__(self):
        return self.short_name

    @property
    def vote_count(self):
        if self.type == SurveyQuestion.YES_NO:
            return self.surveyquestionresponse_set.filter(answer="Y").count()
        else:
            raise RuntimeError("vote_count called on non-vote question")

    class Meta:
        ordering = ["order"]


class SurveyResponse(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=False, null=False)
    survey = models.ForeignKey(Survey, on_delete=models.PROTECT, blank=False, null=False)

    def get_question_response_for(self, question):
        try:
            sqr = SurveyQuestionResponse.objects.get(survey_response=self, question=question)
        except SurveyQuestionResponse.DoesNotExist:
            sqr = SurveyQuestionResponse()
            sqr.survey_response = self
            sqr.question = question
            sqr.save()

        return sqr

    class Meta:
        unique_together = ('user', 'survey',)


class SurveyQuestionResponse(models.Model):
    survey_response = models.ForeignKey(SurveyResponse, on_delete=models.CASCADE, blank=False, null=False)
    question = models.ForeignKey(SurveyQuestion, on_delete=models.PROTECT, blank=False, null=False)
    answer = models.TextField()

    class Meta:
        unique_together = ('survey_response', 'question',)

surveys/forms.py
from django import forms
from django.utils.safestring import mark_safe

from surveys.models import SurveyQuestion
from django.conf import settings


class SurveyFieldMixin:
    def __init__(self, *args, **kwargs):
        self.question = kwargs.pop('question')
        self.response = kwargs.pop('response')
        kwargs['label'] = mark_safe(self.question.prompt)
        kwargs["required"] = self.question.required
        super(SurveyFieldMixin, self).__init__(*args, **kwargs)


class YesNoField(SurveyFieldMixin, forms.Field):
    widget = forms.CheckboxInput

    def __init__(self, *args, **kwargs):
        super(YesNoField, self).__init__(*args, **kwargs)
        if self.response is not None:
            self.initial = self.response.answer == "Y"
        elif self.question.required and settings.TARGET_ENV == "dev":
            self.initial = True

    def to_python(self, value):
        if isinstance(value, str) and value.lower() in ('false', '0'):
            value = "N"
        else:
            value = "Y" if bool(value) else "N"
        return super().to_python(value)


class FreeFormField(SurveyFieldMixin, forms.CharField):
    def __init__(self, *args, **kwargs):
        super(FreeFormField, self).__init__(*args, **kwargs)
        self.widget = forms.Textarea(attrs={'rows': 1})
        if self.response is not None:
            self.initial = self.response.answer
        elif self.question.required and settings.TARGET_ENV == "dev":
            self.initial = 'a'


class SurveyResponseForm(forms.BaseForm):
    SURVEY_QUESTION_HTML_PREFIX = 'sq-'

    user = None
    instance = None

    def __init__(self, *args, survey, user, **kwargs):
        self.survey = survey
        self.base_fields = {}
        self.setUser(user)

        if self.survey.sort_questions:
            questions = survey.surveyquestion_set.order_by('prompt').all()
        else:
            questions = survey.surveyquestion_set.all()

        for survey_question in questions:
            sqr = None if self.instance is None else self.instance.get_question_response_for(survey_question)
            if survey_question.type == SurveyQuestion.YES_NO:
                field = YesNoField(question=survey_question, response=sqr)
            elif survey_question.type == SurveyQuestion.FREEFORM:
                field = FreeFormField(question=survey_question, response=sqr)
            else:
                raise RuntimeError("survey question type '" + survey_question.type + "' not implemented.")

            self.base_fields[SurveyResponseForm.SURVEY_QUESTION_HTML_PREFIX + str(survey_question.pk)] = field

        super(SurveyResponseForm, self).__init__(*args, **kwargs)

    def setUser(self, user):
        self.instance = None if user is None else self.survey.get_response_for(user)

    def is_valid(self):
        return super(SurveyResponseForm, self).is_valid() and self.instance is not None

    def save(self):
        if self.is_valid():
            qd = self.survey.question_dict
            for name, datum in self.cleaned_data.items():
                q_id = int(name.replace(SurveyResponseForm.SURVEY_QUESTION_HTML_PREFIX, ''))
                sqr = self.instance.get_question_response_for(qd[q_id])
                sqr.answer = datum
                print(sqr.answer)
                sqr.save()

surveys/views.py
from django.contrib import messages
import requests
from bs4 import BeautifulSoup
from django.contrib.auth.decorators import login_required
import json

from django.core.exceptions import ValidationError
from django.forms import URLField
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from tld import get_tld

from surveys.forms import SurveyResponseForm
from surveys.models import SurveyQuestion, Survey, SurveyResponse, SurveyQuestionResponse
from urllib.parse import urlparse

def get_redirected(queryset_or_class, lookups, validators):
    """
    Calls get_object_or_404 and conditionally builds redirect URL
    """
    obj = get_object_or_404(queryset_or_class, **lookups)
    for key, value in validators.items():
        if value != getattr(obj, key):
            return obj, obj.get_absolute_url()
    return obj, None


@login_required
def ajax_vote_view(request, *args, **kwargs):
    if request.method == 'POST':
        question = SurveyQuestion.objects.get(id=request.POST.get('question_id'))
        vote_status = request.POST.get(SurveyResponseForm.SURVEY_QUESTION_HTML_PREFIX + str(question.id)) == 'on'
        survey = question.survey

        sr = survey.get_response_for(request.user)
        sqr = sr.get_question_response_for(question)
        sqr.answer = "Y" if vote_status else "N"
        sqr.save()

        return HttpResponse(json.dumps({'vote_count': question.vote_count}))
    else:
        return HttpResponse(status=404)


@login_required
def nominate_charity_view(request, *args, **kwargs):
    if request.method == "POST" and request.POST.get("nominate_charity") is not None:
        survey = Survey.objects.filter(title="Charity of the Month").first()
        website = request.POST.get("website")

        if website[0:7] != 'http://' and website[0:8] != 'https://':
            website = 'http://' + website
        website = urlparse(website).scheme + '://' + urlparse(website).hostname

        try:
            website = URLField().clean(website)
        except ValidationError:
            messages.error(request, "'" + request.POST.get("website") + "' doesn't appear to be a valid web address. Please check it and try again.")

        if get_tld(website) != 'org':
            messages.error(request, 'Organizations nominated must be non-profit, charitable organzations. If ' + request.POST.get("website") + ' is a charity, please <a href="mailto:info@3cross.coop">get in touch</a> and we will submit your nomination manually.', extra_tags='safe')

        if len(messages.get_messages(request)) == 0:
            sq = SurveyQuestion.objects.filter(short_name=website, survey=survey).first()
            if sq is None:
                try:
                    sq = SurveyQuestion()
                    sq.prompt = BeautifulSoup(requests.get(website).content, features="html.parser").title.string
                    sq.type = SurveyQuestion.YES_NO
                    sq.short_name = website
                    sq.survey = survey
                    sq.save()
                except:
                    messages.error(request, "We are unable to verify the web address you submitted (" + request.POST.get("website") + "). Please check it and try again.")

        if len(messages.get_messages(request)) == 0:
            sqr = survey.get_response_for(request.user).get_question_response_for(sq)
            sqr.answer = "Y"
            sqr.save()

        return redirect('/members/surveys/' + survey.slug + ',' + str(survey.id))

@login_required
def survey_view(request, slug, id, *args, **kwargs):
    survey, survey_url = get_redirected(Survey, {'pk': id}, {'slug': slug})
    if request.method == "GET" and survey_url:
        return redirect(survey_url)

    if request.method == "POST":
        survey_form = SurveyResponseForm(request.POST, survey=survey, user=request.user)
        if survey_form.is_valid():
            survey_form.save()
            messages.success(request, "Your responses have been saved.")
            return redirect(reverse_lazy('profile'))
    else:
        survey_form = SurveyResponseForm(survey=survey, user=request.user)

    template = survey.template if survey.template is not None else "survey.html"

    return render(request, template, {"form": survey_form})

templates/about.html
{% extends 'base.html' %}

{% block head_title %}about{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col">
        <h2>Welcome to 3cross!</h2>
        <p>
        3cross Fermentation Cooperative is Massachusetts' first <a href="{% url 'cooperate' %}">community-owned brewery</a>. Our 5,500 square foot space in the basement of 26 Cambridge Street houses a spacious taproom, a small nano-brewery setup and lots of space for expansion. While beer is the core of our business here at 3cross, we have plans for a variety of other fermented foods and drinks in the future. Since the business is owned by you, our customers, we keep our focus on serving our local community. It's unlikely that you'll ever see 3cross beer sold too far from Worcester.
        </p>
        <p>
        Our name references the classic spoke lacing pattern for a bicycle wheel and you'll find elements of bicycle lore and culture throughout the brewery. Since we're cyclists as well as beer lovers, we aim to make 3cross the ideal place to end your next ride. Of course, we also aim to be the perfect place for anyone to enjoy a fresh, local beer.
        </p>
    </div>
</div>
{% endblock %}

templates/apply.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}apply{% endblock %}

{% block content %}
            <div class="row justify-content-center">
                <div class="col">
                    <h2>3cross Membership Application</h2>

                    {% if request.user.is_authenticated %}
                        <p class="centered">
                            You are currently logged in as {{ request.user.full_name }}.
                            Please <a href="{% url 'account_logout' %}?next={% firstof request.path '/' %}">logout</a>
                            to submit a new membership application.</p>
                    {% else %}
                        <form id="coop-app-form" action="?" method="post">
                            {{ user_form|crispy }}
                            {{ member_form|crispy }}
                            {{ address_form|crispy }}
                            {{ survey_form|crispy }}
                            <div class="control-group">
                                {% csrf_token %}
                                {{ user_form.captcha }}
                                <input type="submit" value="Submit Application" class="button" id="coop-app-submit"/>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
{% endblock %}

{% block javascript %}
    <script>

        function hideCityState() {
            $('#div_id_city').hide();
            $('#div_id_state').hide();
        }

        $(function () {
            $(document).ready(function () {
                hideCityState();
            });

            $("#id_postal_code").keyup(function () {
                var zip_in = $(this);
                var zip_box = $('#div_id_postalcode');

                if (zip_in.val().length < 5) {
                    hideCityState();
                } else if (zip_in.val().length > 5) {
                    hideCityState();
                    zip_box.addClass('error');
                } else if ((zip_in.val().length == 5)) {
                    // Make HTTP Request
                    $.ajax({
                        url: "https://api.zippopotam.us/us/" + zip_in.val(),
                        cache: false,
                        dataType: "json",
                        type: "GET",
                        success: function (result, success) {
                            zip_box.addClass("col-4").removeClass("col");
                            $('#div_id_city').show();
                            $('#div_id_state').show();

                            places = result['places'][0];
                            $("#id_city").val(places['place name']);
                            $("#id_state").val(places['state abbreviation']);
                            zip_box.removeClass('error');
                        },
                        error: function (result, success) {
                            hideCityState();
                            zip_box.addClass('error');
                        }
                    });
                }
            });
        });
    </script>
{% endblock %}

{% block css %}
    <style>
        #coop-app-submit {
            min-width: 10em;
            width: 100%;
        }

        #apply .container {
            padding: 1em;
        }

        #apply div {
            padding: .125em;
        }

        #coop-app-submit {
            border: 1px solid #d3d3d3;
            background: #f9f9f9;
            color: black;
            margin: auto;
            margin-top: 8px;
            height: 76px;
            width: 152px;
            font-family: "Open Sans", "Helvetica Neue", Arial, Helvetica, Verdana, sans-serif;
        }

        input:disabled#coop-app-submit, input[disabled]#coop-app-submit {
            box-shadow: none;
            outline: none;
            opacity: 0.1;
            text-decoration: none;
        }


        #apply {
            text-align: left;
        }

        #certbox input, #certbox label {
            display: inline;
        }

        .page-section {
            width: 50%;
            right: 100%;
        }

        .form-text {
            position: relative;
            display: inline-block;
        }

        /* Tooltip text */
        .form-text ul {
            visibility: hidden;
            width: 120px;
            background-color: black;
            color: #fff;
            text-align: center;
            padding: 5px 0;
            border-radius: 6px;

            /* Position the tooltip text - see examples below! */
            position: absolute;
            z-index: 1;
        }

        /* Show the tooltip text when you mouse over the tooltip container */
        .form-text:hover ul {
            visibility: visible;
        }

        .important {
            color: red;
        }
    </style>
{% endblock %}

templates/base.html
{% load static %}
{% load recaptcha3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="3cross Fermentation Cooperative" />
    <meta name="keywords" content="brewery, beer, brewing, cooperative, coop, fermentation, bikes, bicycles" />
    <meta name="description" content="3cross Fermentation Cooperative" />
    <meta name="robots" content="all" />
    <title>{% if request.resolver_match.url_name != 'home' %}{% block head_title %}{% endblock %} | {% endif %}3cross Fermentation Cooperative</title>
    <link rel="icon" type="image/png" href="{% static "pages/images/favicon.png" %}" />
    <link rel="canonical" href="{{ request.scheme }}://{{ request.get_host }}" />
    <link rel='dns-prefetch' href='//s.w.org' />

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link href='https://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
	<link href="{% static "pages/css/styles.css" %}" rel="stylesheet">
    {% block css %}{% endblock %}
</head>
<body id="page">
    <header>
      <a href="#main-menu"
         role="button"
         id="main-menu-toggle"
         class="menu-toggle"
         aria-expanded="false"
         aria-controls="main-menu"
         aria-label="Open main menu">

        <span class="sr-only">Open main menu</span>
        <span class="fa fa-bars" aria-hidden="true"></span>
      </a>

      <nav id="main-menu" role="navigation" class="main-menu" aria-expanded="false" aria-label="Main menu">
        <a href="#"
           role="button"
           id="main-menu-close"
           class="menu-close"
           aria-expanded="false"
           aria-controls="main-menu"
           aria-label="Close main menu">

          <span class="sr-only">Close main menu</span>
          <span class="fa fa-close" aria-hidden="true"></span>
        </a>
        <ul>
                    <li><a href="{% url 'about' %}">about</a></li>
                    <li><a href="{% url 'cooperate' %}">cooperate</a></li>
                    <li><a href="{% url 'visit' %}">visit</a></li>
                    <li><a href="{% url 'find' %}">find our beer</a></li>
                    <li><a href="{% url 'sustainability' %}">sustainability</a></li>
                    <li><a href="{% url 'faq' %}">faq</a></li>
                    <li><a target="new" href="{% url 'shop' %}">webstore</a></li>
                    <li><a href="{% url 'contact' %}">contact</a></li>
                    <li><a href="{% url 'profile' %}">members' portal</a></li>
        </ul>
      </nav>
      <a href="#"
         class="backdrop"
         tabindex="-1"
         aria-hidden="true" hidden></a>
    </header>
	<ul class="slideshow">
		<li><span>Image 01</span></li>
		<li><span>Image 02</span></li>
		<li><span>Image 03</span></li>
		<li><span>Image 04</span></li>
	</ul>
	<div id="logo"><img src="{% static 'pages/images/logo.svg' %}"></div>
    {% if request.resolver_match.url_name != 'home' %}
    <div id="{% if id %}{{ id }}{% else %}{{ request.resolver_match.url_name }}{% endif %}" class="drawer">
          <span class="sr-only">Close page</span>
          <a href="{% url 'home' %}" class="fa fa-close closeToggle" aria-hidden="true"></a>
		<div class="container">
            {% block content %}{% endblock %}
        </div>
	</div>
    {% else %}
        {% block announcements %}{% endblock %}
    {% endif %}

    <div id="hours">
        GPS address:<br/>
        4 Knowlton Ave<br/>
        Worcester, MA 01603<br/><br/>
        retail hours:<br/>
        Sunday - Monday - <strong>closed</strong><br/>
        Tuesday - Friday - <strong>3pm - 7pm</strong><br/>
        Saturday - <strong>12pm - 4pm</strong><br/>
    </div>

    <div id="footer">
            <a href="http://facebook.com/3crossBrewing"><img src="{% static 'pages/images/facebook.svg' %}" alt="follow us on facebook"/></a>
            <a href="http://twitter.com/3crossFermCoop"><img src="{% static 'pages/images/twitter.svg' %}" alt="follow us on twitter"/></a>
            <a href="http://instagram.com/3crossFermCoop"><img src="{% static 'pages/images/instagram.svg' %}" alt="follow us on instagram"/></a>
    </div>

	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.3/jquery.inputmask.min.js"></script>

    {% if recaptcha %}
        {% recaptcha_init %}
        {% recaptcha_ready action_name=request.resolver_match.url_name %}
    {% endif %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	<script src="{% static "pages/js/scripts.js" %}"></script>

    <script>
	    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	    ga('create', 'UA-64999620-1', 'auto');
	    ga('send', 'pageview');
    </script>

    <script src='https://use.fontawesome.com/facf9fa52c.js'></script>

   	<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block javascript %}{% endblock %}
</body>
</html>

templates/charities.html
{% extends 'base.html' %}

{% block head_title %}vote for charities{% endblock %}

{% block content %}

<h2>Charity Nominations</h2>

<h3>Ground Rules:</h3>
<ul>
	<li>Nominate as many charitable organizations as you like.</li>
	<li>Nominees must be bonafide 501(c)(3) charitable organizations.</li>
	<li>At the end of every month, the organization with the most nominations will be designated as the next month's beneficiary.</li>
	<li>Organizations are ineligible for two years following a donation.</li>
</ul>
    <ul class="errorlist">
    {% for message in messages %}
        {% if 'error' in message.tags %}<li>{% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>{% endif %}
    {% endfor %}
    </ul>
<table>
    <thead>
        <tr>
            <th>Organization Name</th>
            <th># of<br/>Nominations</th>
            <th>Nominated?</th>
        </tr>
    </thead>
	<tbody>
    {% for field in form %}
        <tr>
            <td><a href="{{ field.field.question.short_name }}" target="#blank">{{ field.label }}</a></td>
            <td>{{ field.field.question.vote_count }}</td>
            <td>
                <form method="post" data-nominate-charity-url="{% url 'survey_vote' %}">
                    {% csrf_token %}
                    <input type="hidden" name="question_id" value="{{ field.field.question.id }}"/>
                    {{ field }}
                    <input class="save_nomination_status" type="submit" name="nominate" value="Save"/>
                </form>
            </td>
        </tr>
    {% endfor %}
        <tr class="nominee">
            <form id="nominee" action="{% url 'nominate_charity' %}" method="post">
                {% csrf_token %}
                <td class="nominee" colspan="2">
                    <input form="nominee" type="url" name="website" onblur="checkURL(this)" placeholder="Web Address of New Charity Nomination" required id="id_website">
                </td>
                <td><input form="nominee" id="nominate_button" class="button" type="submit" name="nominate_charity" value="Nominate"></td>
            </form>
        </tr>
    </tbody>
</table>
{% endblock %}

{% block javascript %}
<script>
    function checkURL (input) {
      let string = input.value;
      if (!~string.indexOf("http")) {
        string = "http://" + string;
      }
      input.value = string;
      return input
    }

    bind_and_hide = function() {
        $('.save_nomination_status').prop("hidden", true);

        $("input:checkbox").change(function () {
            let form = $(this).closest("form");
            let row = $(this).closest("tr");
            $.ajax({
                url: form.attr("data-nominate-charity-url"),
                type: "POST",
                data: form.serialize(),
                dataType: 'json',
                success: function (data) {
                    row.find('td').eq(1).text(data.vote_count);
                },
                error: function(xhr, status, error) {
                    alert('Error saving nomination!');
                    $(this).prop("checked", $(this).prop("checked"))
                }
            });
        });
    }
    $(document).ready(bind_and_hide);
</script>
{% endblock %}

{% block css %}
<style>
.container ul {
    margin: 2em;
}

table {
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid black;
	padding: .25em;
}

td + td {
	text-align: center;
}

table tr:hover {
    background-color: #ddd;
}

table th {
    background-color: dimgrey;
    color: white;
    text-align: center;
    font-weight: bold;
}

#id_website {
    width: 100%;
}

#nominate_button {
    margin: 0;
    width: auto;
    display: inline;
}

.button:hover {
	background-color: dimgrey;
	color: white;
}
</style>
{% endblock %}

templates/events.html
{% block css %}
<style>
#events, #events .container {
	padding: 0;
}

.event-tile-container {
	padding: 0;
	margin: 0;
	-ms-box-orient: horizontal;
	display: -webkit-box;
	display: -moz-box;
	display: -ms-flexbox;
	display: -moz-flex;
	display: -webkit-flex;
	display: flex;
	-webkit-flex-wrap: wrap;
	flex-wrap: wrap;
}
.event-tile {
	background-color: rgba(200,200,200,0.9);
	background-repeat: no-repeat;
	background-size: 100%;
	border-radius: 1em;
	-webkit-border-radius: 1em;
	-moz-border-radius: 1em;
	border: 1px solid black;
	padding: 1em;
	margin: 0.5em;
	width: 17.5em;
}

.event-tile-image:before {
	content: "";
	display: block;
	padding-top: 100%;
}

</style>
{% endblock %}